version: '3.8'
services:
  api:
    build:
      context: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file: .env
    volumes:
      - ./data:/app/data

  web:
    build:
      context: ./web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file: .env

  subscriber:
    build:
      context: ./api
    volumes:
      - ./data:/app/data
    command: npx ts-node /app/scripts/mock-subscriber.ts
    ports:
      - "${SUBSCRIBER_PORT}:${SUBSCRIBER_PORT}"
    env_file: .env